### ISSUE TITLE
unable to create site using post operation.

### ISSUE THREAD

**Issue by Devraj004** [grelleum/SteelConnection#2] opened 2018-05-31 12:45 UTC
Hi Grelleum,
Thank you for sharing this code with us. I found it very useful for the get operation.
But when i tried to use POST operation it is getting failed. I am trying to create a new site and getting below error.

Traceback (most recent call last):
  File "SCM.py", line 18, in <module>
    response = sconnect.post(resource, data=payload)
  File "C:\Users\trip2185\PycharmProjects\SteelConnect\SteelConnection-master\st
eelconnection.py", line 76, in post
    return self._request(requests.post, resource, data)
  File "C:\Users\trip2185\PycharmProjects\SteelConnect\SteelConnection-master\st
eelconnection.py", line 109, in _request
    self.response.raise_for_status()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\models.py"
, line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://xyz.riverbed.cc/api/scm.config/1.0/org/xyz-POC/sites

Here is my simple code:

import steelconnection
import argparse
import json
import sys
import requests
import getpass

scm_name = 'xyz.riverbed.cc'
username = input("username:")
password = getpass.getpass()

sconnect = steelconnection.Config(scm_name, username, password)

payload = json.dumps({
            'site': 'DKAAA', 'city': 'Copenhagen', 'country': 'Europe'})

resource = '/org/Atkins-POC/sites'
response = sconnect.post(resource, data=payload)
print('Response:', response.status_code, response.reason)
print()
print(response.data)

Actually i am new to RESTAPI , not sure what is wrong with my code.

 need your help.

**Comment by grelleum** [comment] 2018-05-31 22:37
Thank you for trying out my script.  Please let me know if the changes below work for you.

First, the input username and  getpass are built into the object, so if you don't provide these it will prompt for the username and password like this:
`sconnect = steelconnection.Config('xyz.riverbed.cc')`
Nothing wrong with the way you did it, I just figured it would be common enough that the sconnect object should handle that for you.

The sconnect object will accept either json string, or a dictionary and just convert to the right format, so you don't need to use json to convert it.  Additionally, you are required to provide the 'longname' in the payload.  I discovered this by going into the SCM (web browser) and clicked on create new site and see what fields are required.  Also note that country "Europe" is invalid, you would need to use the two letter abbreviation of Denmark.
`payload = {'name': 'DKAAA', 'city': 'Copenhagen', 'country': 'DK', 'longname': 'Denmark Branch office'}`

https://www.willmaster.com/blog/misc/country-name-abbreviation.php
https://support.riverbed.com/apis/scm_beta/scm-2.10.0/scm.config/index.html#!/site/post_org_orgid_sites

The error you are getting is because you are using the org name in the resource call and not the org_id.  So you need to get the ord_id if your don't know it and then use that in your future calls.  To get the org ID, try something like this:
```
org_name = 'MyOrg'
orgs = sconnect.get('orgs').data
org_id = [org['id'] for org in orgs if org_name in org['name']][0]
print('org_id =', org_id)
```
The code above will retrieve all the orgs in that realm, and then look for the ones that include the name you defined in `org_name` , which should be set to the short name of your org.
The short name is the name in the URL when you connect to the SCM through a browser, like:
`    https://XYZ.riverbed.cc/admin/ShortName`
It's using a list comprehension to create a list of all orgs that include that name, so we need to add [0] index to get the first item from the list (should be a list of length one, if done correctly).

Next, your resource should look something like this:
`resource = '/org/{}/sites'.format(org_id)`



Here is a rewrite that should work:
```
import argparse
import sys
import steelconnection

scm_name = 'xyz.riverbed.cc'
org_name = 'My_Org'   ## Change this to the shortname of the org (the name in the browser URL)
sconnect = steelconnection.Config(scm_name)

orgs = sconnect.get('orgs').data
org_id = [org['id'] for org in orgs if org_name in org['name']][0]
print('org_id =', org_id)

payload = {'name': 'DKAAA', 'city': 'Copenhagen', 'country': 'DK', 'longname': 'Denmark Branch office'}

resource = '/org/{}/sites'.format(org_id)
response = sconnect.post(resource, data=payload)
print('Response:', response.status_code, response.reason)
print()
print(response.data)
```

**Comment by grelleum** [comment] 2018-06-04 04:30
I have expanded the documentation and added some more convenience methods to the tool.
I have added a simplified example script to the examples folder.  Please take a look at that.
https://github.com/grelleum/SteelConnection/tree/master/examples

I will go ahead and close this issue.

**Closed by grelleum** 2018-06-04 04:30 UTC

**Comment by grelleum** [comment] 2018-06-08 13:09
Great news - I've modified a bit to integrate the two APIs (config and reporting) so, if you download the latest you'll need to change the initial object creation to look like this:
`sconnect = steelconnection.SConAPI(scm_name)`

**Comment by grelleum** [comment] 2018-06-08 13:13
Additionally, I added a 'lookup' method to lookup the org ID (as well as site and node IDs).  I've updated the 'examples/create_site.py' file to reflect the following change:

replace:
```
orgs = sconnect.get('orgs').data
org_id = [org['id'] for org in orgs if org_name in org['name']][0]
```
with
```
org_id = sconnect.lookup.orgid(org_name)
```

**Comment by Devraj004** [comment] 2018-06-11 04:56
Thank you Grelleum. May I disturb you again ?
Now i am trying to assigned a LAN subnet for the newly created site.  But not working for me.

Here is my code:

import argparse
import sys
import steelconnection

scm_name = 'xyz.riverbed.cc'
org_name = 'xyz-POC'
zone_name = 'DKAAA'
site_name = 'DKAAA'

sconnect = steelconnection.SConAPI(scm_name)

orgs = sconnect.get('orgs').data

org_id = [org['id'] for org in orgs if org_name in org['name']][0]

resource = '/org/{}/networks'.format(org_id)

orgs = sconnect.get((resource)).data


for net in orgs:
    if site_name in net['site']:
        continue
        print (net['id'])
        net_id = net['id']
        payload = {
            "name": "LAN",
            "zone": "DKAAA",
            "site": "DKAAA",
            "netv4": "10.0.0.0/19"
        }
        resource1 = 'networks/{}'.format(net_id)
        print(resource1)
        response = sconnect.put(resource1, data=payload)
        print('Response:', response.status_code, response.reason)
        print()
        print(response.data)

need your help again.

**Comment by grelleum** [comment] 2018-06-11 12:21
I edited your comment to wrap the code in triple back-ticks.  ``
This allows the indentation to be shown correctly.
https://guides.github.com/features/mastering-markdown/

The issue I see is that all the code after the `continue` statement will never be executed.  This is because it is at the same level of indentation as the `continue` statement, which is indented under the `if` statement.  Therefore `if site_name in net['site']:`, then we run all the code below that, and the first statement there is `continue`, which causes the loop to continue with the next value and stop processing of the lines below it.

Since you are looking for a specific network that matches that site, you want to take action when it matches, so you should remove the `continue` so that the rest of the code gets executed.  Additionally, you could add a `break` to the end of that code, since you do not expect any other networks to match that site, and you would not want your code to assign the same subnet to two different networks.

I have not checked your payload - it may work or it may fail because there is not enough data provided.  That's the tricky part of the API is not knowing what is the minimum required for each specific command.

```python
for net in orgs:
    if site_name in net['site']:
        # continue  # Remove this line, this stops the rest of the code from executing
        print (net['id'])
        net_id = net['id']
        payload = {
            "name": "LAN",
            "zone": "DKAAA",
            "site": "DKAAA",
            "netv4": "10.0.0.0/19"
        }
        resource1 = 'networks/{}'.format(net_id)
        print(resource1)
        response = sconnect.put(resource1, data=payload)
        print('Response:', response.status_code, response.reason)
        print()
        print(response.data)
        break  # Added break here - we found what we want, lets break out of the loop.
```

**Comment by Devraj004** [comment] 2018-06-11 13:36
My bad. Not sure why was added the continue statement here.

Many thanks for your quick response. I tried the code but getting 404 error.

Traceback (most recent call last):
  File "SCM_PUT.py", line 34, in <module>
    response = sconnect.put(resource1, data=payload)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\steelconnection\ste
elconnection.py", line 99, in put
    return self._request(self.session.put, 'config', resource, data)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\steelconnection\ste
elconnection.py", line 128, in _request
    self.response.raise_for_status()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\models.py"
, line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://xyz.riverbed.cc/api/scm.config/1.0/networks/net-Net-56a53e074367a6ec

**Comment by grelleum** [comment] 2018-06-11 18:07
You need to look at the output for a site or a network to know what keys are in the data.  So when you try to match the site_name agains the network['site'] you won't get a match because the 'site' is not a name like "DKAAA" but an ID for that site like "site-DKAAA-e8f4c3582ddf9550".  On the otherhand, you could match the net['name'] key, since that stores the name you gave the site.

However - if you are looking to both create a site and then modify that site you just created, the API will return the site that gets created, so you don't have to look for the network.

```python
>>> resource = '/org/{}/sites'.format(org_id)
>>> payload = {'name': 'DKAAA', 'city': 'Copenhagen', 'country': 'DE', 'longname': 'Denmark Remote office'}
>>> new_site = sconnect.post(resource, data=payload).data
>>> new_site
{'sitelink_pool_v4': None, 'org': 'org-grellusKVM-0a501e7f27b2c03e', 'city': 'Copenhagen', 'street_address': None, 'networks': ['net-Net-11ab344dc06831d8'], 'agent_site': '0', 'sitelink_leafs': [], 'sitelink_leaf': None, 'id': 'site-DKAAA-e8f4c3582ddf9550', 'radius_servers': '[]', 'extra_segments': [], 'size': '2', 'xlan': '0', 'sitelink_port': '4500', 'timezone': 'America/Los_Angeles', 'sitelink_vip': '198.18.0.16', 'uid': '15', 'longname': 'Denmark Remote office', 'sitelink_vip6': 'fd6c:98eb::198.18.0.16', 'country': 'DE', 'breakout_sitelink_site': None, 'dns_name': None, 'name': 'DKAAA', 'breakout_preference': [], 'uplinks': ['uplink-Uplink-77641dd44a477867'], 'tags': None, 'dnsroutes': None}
>>> 
>>> new_site['networks']
['net-Net-11ab344dc06831d8']
>>> net_id = new_site['networks'][0]
>>> net_id
'net-Net-11ab344dc06831d8'
>>> 
>>> net = sconnect.get('/network/' + net_id).data
>>> net
{'org': 'org-grellusKVM-0a501e7f27b2c03e', 'netv6': 'fd00:ced0:ced0:102::/64', 'dhcps_options': '# Example for TFTP boot (BOOTP/PXE)\n#option filename pxelinux.0\n#option servername server.mydomain.local\n#option serveraddress 192.168.1.1\n\n# Example for NTP server\n#option ntp-server,192.168.0.4,10.10.0.5\n\n# Example for DNS server\n#option dns-server,192.168.0.1,192.168.0.2\n\n# Example for domain search\n#option domain-search,domain.local\n\n# Example to send SIP server based on substring match of vendor ID\n#option vendor:Phone,sip-server,192.168.1.2\n\n# Example HTTP proxy configuration string using vendor attributes\n#option vendor:Riverbed,42,"address:port"\n', 'site': 'site-DKAAA-e8f4c3582ddf9550', 'gw_noauto': '0', 'devices': [], 'netv4': '10.20.252.0/24', 'dhcps_range_end': '0xfe', 'zone': 'segment-LAN-a14ed9c0905e0851', 'dhcps_leasetime': '720', 'id': 'net-Net-11ab344dc06831d8', 'gwv4': '0x1', 'gwv6': '0x1', 'primary': '1', 'dhcps_range_start': '0x2', 'name': 'Net', 'breakout_sitelink_site': None, 'ra': '0', 'wans': ['wan-RouteVPN-e7d211760427fb07'], 'breakout_preference': [], 'routes': [], 'lnets': [], 'nodenetcfgs': []}
>>> 
>>> 
>>> net['netv4'] = '10.0.0.0/19'
>>> net_update = sconnect.put('/network/' + net_id, data=net).data
>>> 
>>> net_update
{'org': 'org-grellusKVM-0a501e7f27b2c03e', 'netv6': 'fd00:ced0:ced0:102::/64', 'dhcps_options': '# Example for TFTP boot (BOOTP/PXE)\n#option filename pxelinux.0\n#option servername server.mydomain.local\n#option serveraddress 192.168.1.1\n\n# Example for NTP server\n#option ntp-server,192.168.0.4,10.10.0.5\n\n# Example for DNS server\n#option dns-server,192.168.0.1,192.168.0.2\n\n# Example for domain search\n#option domain-search,domain.local\n\n# Example to send SIP server based on substring match of vendor ID\n#option vendor:Phone,sip-server,192.168.1.2\n\n# Example HTTP proxy configuration string using vendor attributes\n#option vendor:Riverbed,42,"address:port"\n', 'site': 'site-DKAAA-e8f4c3582ddf9550', 'gw_noauto': '0', 'devices': [], 'netv4': '10.0.0.0/19', 'dhcps_range_end': '0xfe', 'zone': 'segment-LAN-a14ed9c0905e0851', 'dhcps_leasetime': '720', 'id': 'net-Net-11ab344dc06831d8', 'gwv4': '0x1', 'gwv6': '0x1', 'primary': '1', 'dhcps_range_start': '0x2', 'name': 'Net', 'breakout_sitelink_site': None, 'ra': '0', 'wans': ['wan-RouteVPN-e7d211760427fb07'], 'breakout_preference': [], 'routes': [], 'lnets': [], 'nodenetcfgs': []}
>>> 
```

**Comment by grelleum** [comment] 2018-06-11 18:10
By the way, I am considering removing the `.data` requirement and have the get/post/put commands just return the data, without having to specify `.data`.  I think that might be simpler and the response would still be available by accessing sconnect.response.

**Comment by Devraj004** [comment] 2018-06-12 13:18
Excellent Sir! you are really genius. 
Thank you so much for the simple and excellent explanation. 
I think the key point that i was missing in code was 'data = net' in the put request.
Removing the .data requirement is also a good idea as response would still be available if require.

Many Thanks again

**Comment by grelleum** [comment] 2018-06-13 17:05
Excellent.
I have uploaded a new version that does away with the requirement to add `.data` to get the result.  Now all calls to the object will simply return the resulting data.  If you need to get to the actual response from the server, then you can access sconnect.response.
You can update your copy by using:
```
python3 -m pip install --upgrade steelconnection
# -or-
python3 -m pip install --upgrade steelconnection
```

**Comment by Devraj004** [comment] 2018-06-21 14:35
Hi Grelleum,
Now i am trying to create multiple sites using steelconnect RESTAPI. My excel sheet is looks like below.

Name | City | Longname | Country
-- | -- | -- | --
DKAAA | Aarhus | Denmark Branch office | DK
DKCGA | Copenhagen | Denmark Head office | DK

I have created below script to fetch the data from excel sheet and create the dictionary. 
import argparse
import sys
import steelconnection
import xlrd
import time

scm_name = 'xyz.riverbed.cc'
org_name = 'xyz-POC' 

sconnect = steelconnection.SConAPI(scm_name)
org_id, orgs = sconnect.lookup.org(org_name)

print('org_id =', org_id)

wb = xlrd.open_workbook(filename='abc.xlsx')
sheet = wb.sheet_by_index(0)

j=1
data1 = [[sheet.cell_value(r,c) for c in range(sheet.ncols-1)] for r in range(sheet.nrows)]

for output in data1:
    while(j < sheet.nrows):
        payload = dict(zip(data1[0], data1[j]))
        j = j + 1
        resource = '/org/{}/sites'.format(org_id)
        response = sconnect.post(resource,payload)
        print(response)
        break


But my script is not working and getting below error.

Traceback (most recent call last):
  File "SCM-POST-sites.py", line 35, in <module>
    response = sconnect.post(resource,payload)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\steelconnection\steelconnection.py", line 125, in post
    data=data,
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\steelconnection\steelconnection.py", line 167, in _request
    raise RuntimeError(error)
RuntimeError:   400 - Bad Request
Details:        Name, Long Name and City are required parameters
URL:            https://xyz.riverbed.cc/api/scm.config/1.0/org/org-xyz-8f25dd18b91a71c1/sites
Data Sent:      '{"Name": "DKAAA", "City": "Aarhus", "Longname": "Denmark Branch office", "Country": "DK"}'

Any help Sir ?

**Comment by grelleum** [comment] 2018-06-21 17:46
I think the problem is that the keys in the data are case-sensitive.
Try changing this line:
`payload = dict(zip(data1[0], data1[j]))`
to this:
`payload = dict(zip(data1[0].lower(), data1[j]))`

**Comment by Devraj004** [comment] 2018-06-22 07:41
Oh, that's really nice. I changed the keys to lower in excel sheet and that works.
as with the above changes in script got AttributeError: 'list' object has no attribute 'lower' 

  payload = dict(zip(data1[0].lower(), data1[j]))
AttributeError: 'list' object has no attribute 'lower'

Many thanks for your help.

**Comment by Devraj004** [comment] 2018-07-11 13:51
Hi Grelleum,
I am trying to register appliance node with below script. After running the script
SCM generates syslog message that a  node with serial':'xxxxxxxxxxxx has been registered with core service, but when i check the device in appliance tab no appliace and location found there.

import argparse
import sys
import steelconnection

scm_name = 'xyz.riverbed.cc'
org_name = 'xyz-POC' 
sconnect = steelconnection.SConAPI(scm_name)

org_id, orgs = sconnect.lookup.org(org_name)


print('org_id =', org_id)


payload = {'site':'DKAAA','serial':'xxxxxxxxxxxx'}

resource = '/org/{}/node/register'.format(org_id)

response = sconnect.post(resource, data=payload)

print(response)

 I am not sure if we can register the hardware using RestAPI ? or any thing wrong with my script.

Apologies for my too many queries.

**Comment by gm127f** [comment] 2018-07-11 14:36
Since the appliance says it was registered, it should show up in the appliance list.  If you click on Appliances and then put the serial number in the search box, you should see the appliance, but it will not be in the site DKAAA.

The issue is that your site is "invalid" as you need to provide the site 'id' rather than the name.
try this:
```
site_id, site = sconnect.lookup.site('DKAAA', org_id)
payload = {'site': site_id,' serial':'xxxxxxxxxxxx'}

resource = '/org/{}/node/register'.format(org_id)
response = sconnect.post(resource, data=payload)
```

**Comment by grelleum** [comment] 2018-07-11 14:46
Since the appliance says it was registered, it should show up in the appliance list.  If you click on Appliances and then put the serial number in the search box, you should see the appliance, but it will not be in the site DKAAA.

The issue is that your site is "invalid" as you need to provide the site 'id' rather than the name.
try this:
```
site_id, site = sconnect.lookup.site('DKAAA', org_id)
payload = {'site': site_id,' serial':'xxxxxxxxxxxx'}

resource = '/org/{}/node/register'.format(org_id)
response = sconnect.post(resource, data=payload)
```

**Comment by Devraj004** [comment] 2018-07-12 07:02
A big salute to you. After adding the site_id it works. 

Many thanks Sir
